name: Push to AWS

on: [push, pull_request]

jobs:
  PushAWS:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [macos-10.15]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Install Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7'
        architecture: 'x64'
    - name: Install Python Dependencies
      run: |
        sudo -H python3 -m pip install requests
        sudo -H python3 -m pip install beautifulsoup4
        sudo -H python3 -m pip install awscli
        sudo -H python3 -m pip install dmgbuild
    - name: MacOS Signing
      if: matrix.os == 'macos-10.15'
      run: |
        openssl enc -aes-256-cbc -a -d -in ./release_script/mac_only/Certificates.p12.enc -out ./release_script/mac_only/Certificates.p12 -k $MAC_DECRYPT_KEY
        md5 ./release_script/mac_only/Certificates.p12
        bash release_script/mac_only/add-osx-cert.sh
      env:
        MAC_DECRYPT_KEY: ${{ secrets.MAC_DECRYPT_KEY }}
    - name: Processing MacOS
      if: matrix.os == 'macos-10.15'
      run: |
        mkdir $GITHUB_WORKSPACE/temp
        cd $GITHUB_WORKSPACE/temp
        curl -O -L --insecure https://download.processing.org/processing-3.5.3-macosx.zip
        unzip processing-3.5.3-macosx.zip
        mv Processing.app /Applications/Processing.app
        echo ${GITHUB_WORKSPACE}/release_script/mac_only>>$GITHUB_PATH
        chmod +x $GITHUB_WORKSPACE/release_script/mac_only/processing-java
        mkdir -p ~/Documents/Processing/libraries/
        cp -a $GITHUB_WORKSPACE/OpenBCI_GUI/libraries/ ~/Documents/Processing/libraries/
        mkdir -p ~/sketchbook/libraries/
        cp -a $GITHUB_WORKSPACE/OpenBCI_GUI/libraries/ ~/sketchbook/libraries/
        echo ~/sketchbook/libraries/
        ls ~/sketchbook/libraries/
    - name: Run Make Release Script - TEST
      if: matrix.os == 'macos-10.15'
      run: |
        cd $GITHUB_WORKSPACE
        $GITHUB_WORKSPACE/release_script/mac_only/processing-java --sketch=$GITHUB_WORKSPACE/OpenBCI_GUI_1/ --output=$GITHUB_WORKSPACE/OpenBCI_GUI/OpenBCI_GUIapplication.macosx --export
    - name: Run Make Release Script
      if: matrix.os == 'macos-10.15'
      run: |
        cd $GITHUB_WORKSPACE
        python3 $GITHUB_WORKSPACE/release_script/make-release.py --no-prompts
        GUI_COMMIT_TIME=`cat temp/timestamp.txt`
        GUI_VERSION_STRING=`cat temp/versionstring.txt`
    - name: MacOS Publish
      if: matrix.os == 'macos-10.15'
      run: |
        suaws s3 rm s3://openbci-gui/${GITHUB_REF}/latest  --recursive --exclude "*" --include "openbcigui_*_macosx.dmg"
        aws s3 cp $TRAVIS_BUILD_DIR/. s3://openbci-gui/${GITHUB_REF}/${GUI_VERSION_STRING}_${GUI_COMMIT_TIME}  --recursive --exclude "*" --include "openbcigui_*_macosx.dmg"
        aws s3 cp $TRAVIS_BUILD_DIR/. s3://openbci-gui/${GITHUB_REF}/latest  --recursive --exclude "*" --include "openbcigui_*_macosx.dmg"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}